[package]
name = "fastgmad"
version = "0.3.10"
edition = "2024"
authors = ["William Venner, VermeilChan"]
license = "MIT OR Apache-2.0"
description = "Fast gmad implementation"
repository = "https://github.com/VermeilChan/fastgmad"
resolver = "2"

[features]
binary = ["dep:libloading", "dep:ctrlc"]

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
memchr = "2.7.5"
byteorder = "1.5.0"
uuid = { version = "1.17.0", features = ["v4"] }
log = "0.4.27"
thiserror = "2.0.12"

ctrlc = { version = "3.4.7", optional = true }
libloading = { version = "0.8.8", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["stringapiset"] }

[dev-dependencies]
lazy_static = "1.5.0"
sysreq = "0.1.6"
zip = "4.3.0"
