[workspace]
members = ["fastgmad-lib", "fastgmad-bin"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
incremental = false
debug = false
debug-assertions = false
overflow-checks = false