[build]
rustc-wrapper = "sccache"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64-v3", "-C", "linker=lld"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3", "-C", "link-arg=-fuse-ld=mold"]